component_name = "foo_svg_services"
solution_path = "vc17\\svg-services.sln"
output_path = "component-packages"
x86_build_path = "vc17\\release-win32-v143"
x64_build_path = "vc17\\release-x64-v143"
licence_file = "cargo-about.txt"
